;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-newline-and-maybe-indent
	indent-for-tab-command
	keyboard-escape-quit
	))

(setq mc/cmds-to-run-once
      '(
	duplicate-region-or-line-below
	kill-region
	recentf-open-files
	))
