;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-newline-and-maybe-indent
	indent-for-tab-command
	keyboard-escape-quit
	multiple-cursors-mode
	recompile
	))

(setq mc/cmds-to-run-once
      '(
	astyle-buffer
	duplicate-region-or-line-below
	end-of-buffer
	eval-buffer
	ignore
	kill-region
	overwrite-mode
	recentf-open-files
	tab-line-switch-to-next-tab
	tab-line-switch-to-prev-tab
	))
